services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    env_file:
      - .env.local
    volumes:
      - ./data:/data

  ewagifts-rest-api:
    container_name: ewagifts-rest-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: curl -f http://localhost:8090 || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - 8090:8090
    expose:
      - 8090
    env_file:
      - .env.local
    depends_on:
      - redis-stack
